/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-03-11 21:20:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.AdminLTE.User;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import crud.User;
import pagecreate.pageUserDAO;
import pagecreate.pageUser;
import java.util.ArrayList;

public final class example_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("crud.User");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("pagecreate.pageUserDAO");
    _jspx_imports_classes.add("pagecreate.pageUser");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // Get distinct university names
    List<String> distinctUniNames = new pageUserDAO().getDistinctUniNames();

      out.write('\r');
      out.write('\n');

int userId = Integer.parseInt(request.getParameter("id"));
pageUser user1 = new pageUserDAO().getUserById(userId);
String[] paragraphArray = user1.getDesc().split("\\n");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <title>University Guide</title>\r\n");
      out.write("  <!-- External CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../plugins/fontawesome-free/css/all.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../dist/css/adminlte.min.css\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- Internal CSS -->\r\n");
      out.write("  <style>\r\n");
      out.write("    .color-ful {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      justify-content: start;\r\n");
      out.write("      align-items: start;\r\n");
      out.write("      max-width: 900px;\r\n");
      out.write("      margin: 0px auto;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      background-color: #FFFFFF; /* Change this to the desired color */\r\n");
      out.write("      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("    .name {\r\n");
      out.write("      color: #FFFFFF;\r\n");
      out.write("    }\r\n");
      out.write("    h1 {\r\n");
      out.write("      font-size: 24px;\r\n");
      out.write("      margin: 30px 0;\r\n");
      out.write("    }\r\n");
      out.write("    p {\r\n");
      out.write("      text-align: justify;\r\n");
      out.write("      line-height: 1.6;\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .my-img {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 450px;\r\n");
      out.write("      object-fit: cover;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    .logo {\r\n");
      out.write("      width: 65px;\r\n");
      out.write("      height: 65px;\r\n");
      out.write("      border-radius: 50%;\r\n");
      out.write("      line-height: 45px;\r\n");
      out.write("    }\r\n");
      out.write("    .container {\r\n");
      out.write("      background-color: #36384E;\r\n");
      out.write("      padding: 15px;\r\n");
      out.write("      color: white;\r\n");
      out.write("    }\r\n");
      out.write("    .container p {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .main-footer {\r\n");
      out.write("      background-color: #198057;\r\n");
      out.write("      color: #FFFFFF;\r\n");
      out.write("    }\r\n");
      out.write("    .form-control::placeholder {\r\n");
      out.write("      font-size: 0.95rem;\r\n");
      out.write("    }\r\n");
      out.write("    [class*=sidebar-dark-] {\r\n");
      out.write("      background-color: #568a54;\r\n");
      out.write("    }\r\n");
      out.write("    [class*=sidebar-dark-] .sidebar a {\r\n");
      out.write("      color: #FFFFFF;\r\n");
      out.write("    }\r\n");
      out.write("    .content-wrapper {\r\n");
      out.write("      background-color: white;\r\n");
      out.write("    }\r\n");
      out.write("    .card-header {\r\n");
      out.write("      background-color: #229985;\r\n");
      out.write("    }  \r\n");
      out.write("    .card-title {\r\n");
      out.write("      color: white;\r\n");
      out.write("    }\r\n");
      out.write("    .content-wrapper {\r\n");
      out.write("    background-color: #FCFCFC;\r\n");
      out.write("}\r\n");
      out.write("  .two{\r\n");
      out.write("    width: 50px;\r\n");
      out.write("    height : 50px;\r\n");
      out.write("    border-radius: 50%;}\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"hold-transition sidebar-mini\">\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("  <!-- Navbar -->\r\n");
      out.write("  <nav class=\"main-header navbar navbar-expand navbar-white navbar-light\">\r\n");
      out.write("    <ul class=\"navbar-nav\">\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" data-widget=\"pushmenu\" href=\"#\" role=\"button\"><i class=\"fas fa-bars\"></i></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-sm-inline-block\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AdminLTE/User/userHome.jsp\" class=\"nav-link\">Home</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-sm-inline-block\">\r\n");
      out.write("        <a href=\"#\" class=\"nav-link\">Contact</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </nav>\r\n");
      out.write("  \r\n");
      out.write("  <!-- Sidebar -->\r\n");
      out.write("  <aside class=\"main-sidebar sidebar-dark-primary elevation-4\">\r\n");
      out.write("    <a href=\"../index3.html\" class=\"brand-link\">\r\n");
      out.write("      <img src=\"l.jpg\" alt=\"AdminLTE Logo\" class=\"brand-image img-circle elevation-3\" style=\"opacity: .8\">\r\n");
      out.write("      <span class=\"brand-text font-weight-light\">University Guide</span>\r\n");
      out.write("    </a>\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("      <div class=\"user-panel mt-3 pb-3 mb-3 d-flex\">\r\n");
      out.write("        <div class=\"image\">\r\n");
      out.write("          <img src=\"logo.jpg\" class=\"img-circle elevation-2\" alt=\"User Image\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"info\">\r\n");
      out.write("          <a href=\"#\" class=\"d-block\">University Guide</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <nav class=\"mt-2\">\r\n");
      out.write("<ul class=\"nav nav-pills nav-sidebar flex-column\" data-widget=\"treeview\" role=\"menu\" data-accordion=\"false\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"three.jsp\" class=\"nav-link\">\r\n");
      out.write("              <i class=\"nav-icon fas fa-search\"></i>\r\n");
      out.write("              <p>\r\n");
      out.write("                Search\r\n");
      out.write("               \r\n");
      out.write("              </p>\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("          </li>\r\n");
      out.write("          <!-- Iterate over distinct university names -->\r\n");
      out.write("          ");
 for(String uniName : distinctUniNames) { 
      out.write("\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"fas fa-university nav-icon\"></i>\r\n");
      out.write("                <p>");
      out.print( uniName );
      out.write("<i class=\"right fas fa-angle-left\"></i></p>\r\n");
      out.write("              </a>\r\n");
      out.write("              <ul class=\"nav nav-treeview\">\r\n");
      out.write("                <!-- Retrieve user list for each university -->\r\n");
      out.write("                ");
 List<pageUser> userList = new pageUserDAO().getUserByName(uniName); 
      out.write("\r\n");
      out.write("                ");
 for(pageUser user : userList) { 
      out.write("\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"example1.jsp?id=");
      out.print( user.getId() );
      out.write("\" class=\"nav-link\">\r\n");
      out.write("                      <i class=\"fas fa-map-marker-alt nav-icon\"></i>\r\n");
      out.write("                      <p>");
      out.print( user.getLocation() );
      out.write("</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("          ");
 } 
      out.write("\r\n");
      out.write("          \r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("  </aside>\r\n");
      out.write("  \r\n");
      out.write("  <!-- Content Wrapper -->\r\n");
      out.write("  <div class=\"content-wrapper\">\r\n");
      out.write("    <div class=\"color-ful\">\r\n");
      out.write("      <img class=\"my-img\" src=\"../../img/");
      out.print( user1.getImage() );
      out.write("\" alt=\"\">\r\n");
      out.write("      <h1><img class=\"two\" src=\"../../img/");
      out.print( user1.getLogo() );
      out.write("\" alt=\"\">");
      out.print( user1.getLocation() );
      out.print( user1.getUniname() );
      out.write("</h1>\r\n");
      out.write("      ");
 
        // Iterate over paragraph array
        for (String paragraph : paragraphArray) {
      
      out.write("\r\n");
      out.write("        <p>");
      out.print( paragraph );
      out.write("</p>\r\n");
      out.write("      ");

        }
      
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <!-- Main Footer -->\r\n");
      out.write("  <footer class=\"main-footer\">\r\n");
      out.write("    <div class=\"float-right d-none d-sm-block\">\r\n");
      out.write("      <b><a href=\"../loginAndregister/login.jsp\" class=\"btn btn-primary\">Go Admin</a></b>\r\n");
      out.write("    </div>\r\n");
      out.write("    <strong>Copyright &copy; 2023-2024 <a href=\"https://adminlte.io\">University Admissions Guide</a>.</strong> All rights reserved.\r\n");
      out.write("  </footer>\r\n");
      out.write("  \r\n");
      out.write("  <!-- Control Sidebar -->\r\n");
      out.write("  <aside class=\"control-sidebar control-sidebar-dark\"></aside>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Scripts -->\r\n");
      out.write("<script src=\"../plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"../plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"../dist/js/adminlte.min.js\"></script>\r\n");
      out.write("<script src=\"../dist/js/demo.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
