/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-03-11 20:11:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.AdminLTE.PageCreate;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import pagecreate.pageUser;
import pagecreate.pageUserDAO;
import crud.User;
import crud.UserDAO;
import java.util.ArrayList;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("crud.User");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("crud.UserDAO");
    _jspx_imports_classes.add("pagecreate.pageUserDAO");
    _jspx_imports_classes.add("pagecreate.pageUser");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;  charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String searchQuery = request.getParameter("search");

List<pageUser> userList;
if (searchQuery != null && !searchQuery.isEmpty()) {
	userList = new pageUserDAO().searchUsers(searchQuery);
} else {
	userList = new pageUserDAO().getAllUsers();
}

      out.write('\r');
      out.write('\n');

List<User> check = new UserDAO().getAllUsers();

// Initialize linkData array with the size of check list
String[] linkData = new String[check.size()];


// Loop through each user and add their link to linkData array
int i = 0;
for (User a : check) {
	linkData[i] = a.getLink();
	i++;
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Blog/App</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback\">\r\n");
      out.write("<!-- Font Awesome Icons -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"../plugins/fontawesome-free/css/all.min.css\">\r\n");
      out.write("<!-- Theme style -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../dist/css/adminlte.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("	.main-footer {\r\n");
      out.write("    background-color: #198057;\r\n");
      out.write("    color: #FFFFFF;\r\n");
      out.write("}\r\n");
      out.write(".form-control::placeholder {\r\n");
      out.write("  font-size: 0.95rem; /* Change this value to your desired font size */\r\n");
      out.write("}\r\n");
      out.write("[class*=sidebar-dark-] {\r\n");
      out.write("    background-color: #568a54;\r\n");
      out.write("}\r\n");
      out.write("[class*=sidebar-dark-] .sidebar a {\r\n");
      out.write("    color: #FFFFFF;\r\n");
      out.write("}\r\n");
      out.write(".content-wrapper {\r\n");
      out.write("    background-color: white;\r\n");
      out.write("}\r\n");
      out.write(".card-header {\r\n");
      out.write("    background-color: #229985;\r\n");
      out.write("\r\n");
      out.write("}  \r\n");
      out.write(".card-title {\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("   \r\n");
      out.write("</style>\r\n");
      out.write("<body class=\"hold-transition sidebar-mini\">\r\n");
      out.write("	<div class=\"wrapper\">\r\n");
      out.write("		<nav\r\n");
      out.write("			class=\"main-header navbar navbar-expand navbar-white navbar-light\">\r\n");
      out.write("			<!-- Left navbar links -->\r\n");
      out.write("			<ul class=\"navbar-nav\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" data-widget=\"pushmenu\"\r\n");
      out.write("					href=\"#\" role=\"button\"><i class=\"fas fa-bars\"></i></a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("					data-widget=\"navbar-search\" href=\"#\" role=\"button\"> <i\r\n");
      out.write("						class=\"fas fa-search\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("					<div class=\"navbar-search-block\">\r\n");
      out.write("						<form class=\"form-inline\" method=\"get\" action=\"\">\r\n");
      out.write("\r\n");
      out.write("							<div class=\"input-group input-group-sm\">\r\n");
      out.write("								<input class=\"form-control form-control-navbar\" name=\"search\"\r\n");
      out.write("									type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("								<div class=\"input-group-append\">\r\n");
      out.write("									<button class=\"btn btn-navbar\" type=\"submit\">\r\n");
      out.write("										<i class=\"fas fa-search\"></i>\r\n");
      out.write("									</button>\r\n");
      out.write("									<button class=\"btn btn-navbar\" type=\"button\"\r\n");
      out.write("										data-widget=\"navbar-search\">\r\n");
      out.write("										<i class=\"fas fa-times\"></i>\r\n");
      out.write("									</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("\r\n");
      out.write("					</div></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<aside class=\"main-sidebar sidebar-dark-primary elevation-4\">\r\n");
      out.write("			<a href=\"\" class=\"brand-link\"> <img\r\n");
      out.write("				src=\"l.jpg\" alt=\"AdminLTE Logo\"\r\n");
      out.write("				class=\"brand-image img-circle elevation-3\" style=\"opacity: .8\">\r\n");
      out.write("				<span class=\"brand-text font-weight-light\"> University Guide\r\n");
      out.write("			</span>\r\n");
      out.write("			</a>\r\n");
      out.write("			<div class=\"sidebar\">\r\n");
      out.write("				<div class=\"user-panel mt-3 pb-3 mb-3 d-flex\">\r\n");
      out.write("					<div class=\"image\">\r\n");
      out.write("						<img src=\"lull.jpg\"\r\n");
      out.write("							class=\"img-circle elevation-2\" alt=\"User Image\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"info\">\r\n");
      out.write("						<a href=\"#\" class=\"d-block\"> Admin </a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<nav class=\"mt-2\">\r\n");
      out.write("					<ul class=\"nav nav-pills nav-sidebar flex-column\"\r\n");
      out.write("						data-widget=\"treeview\" role=\"menu\" data-accordion=\"false\">\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"#\" class=\"nav-link\"> <i\r\n");
      out.write("								class=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("								<p>\r\n");
      out.write("									Pages <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("								</p>\r\n");
      out.write("						</a>\r\n");
      out.write("							<ul class=\"nav nav-treeview\">\r\n");
      out.write("								<li class=\"nav-item\"><a\r\n");
      out.write("									href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AdminLTE/loginAndregister/home.jsp\"\r\n");
      out.write("									class=\"nav-link\"> <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("										<p>University</p>\r\n");
      out.write("								</a></li>\r\n");
      out.write("\r\n");
      out.write("							</ul>\r\n");
      out.write("							<ul class=\"nav nav-treeview\">\r\n");
      out.write("								<li class=\"nav-item\"><a\r\n");
      out.write("									href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AdminLTE/User/userHome.jsp\"\r\n");
      out.write("									class=\"nav-link\"> <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("										<p>User</p>\r\n");
      out.write("								</a></li>\r\n");
      out.write("\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li class=\"nav-item\"><a href=\"../loginAndregister/logout.jsp\"\r\n");
      out.write("							class=\"nav-link\"> <i class=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("								<p>\r\n");
      out.write("									Logout <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("								</p>\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("					</ul>\r\n");
      out.write("				</nav>\r\n");
      out.write("				<!-- /.sidebar-menu -->\r\n");
      out.write("			</div>\r\n");
      out.write("		</aside>\r\n");
      out.write("		<div class=\"content-wrapper\">\r\n");
      out.write("			<div class=\"content-header\">\r\n");
      out.write("				<div class=\"container-fluid\">\r\n");
      out.write("					<div class=\"row mb-2\">\r\n");
      out.write("						<div class=\"col-sm-6\">\r\n");
      out.write("							<h1 class=\"m-0\"></h1>\r\n");
      out.write("						</div>\r\n");
      out.write("						<br>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("\r\n");
      out.write("<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AdminLTE/PageCreate/add.jsp?id=");
      out.print( userList.size() );
      out.write("\" class=\"btn btn-warning\"> စာမျက်နှာအသစ်တစ်ခုဖန်တီးရန် </a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					");

					if (!userList.isEmpty()) {
					
      out.write("\r\n");
      out.write("					<div class=\"float-right d-none d-sm-inline\">\r\n");
      out.write("						<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/DeleteAll\"\r\n");
      out.write("							onclick=\"alert('Are you sure you want to delete all?');\"\r\n");
      out.write("							type=\"button\" class=\"btn btn-danger\"> DeleteAll </a>\r\n");
      out.write("					</div>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"content\">\r\n");
      out.write("				");

				if (userList.isEmpty()) {
				
      out.write("\r\n");
      out.write("				<div class=\"row justify-content-center\">\r\n");
      out.write("					<div class=\"col-md-6\">\r\n");
      out.write("						<div class=\"alert alert-info text-center\" role=\"alert\">\r\n");
      out.write("							ပြသရန်မရှိပါ.</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				} else {
				
      out.write("\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-12\">\r\n");
      out.write("						<div class=\"card\">\r\n");
      out.write("							<div class=\"card-header\">\r\n");
      out.write("								<h3 class=\"card-title\">Page Create Blog</h3>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<div class=\"card-body\">\r\n");
      out.write("								<table class=\"table table-bordered\">\r\n");
      out.write("									<thead>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<th style=\"width: 20px\">အမှတ်စဉ်</th>\r\n");
      out.write("											<th>တက္ကသိုလ် အမည်</th>\r\n");
      out.write("											<th>တည်နေရာ</th>\r\n");
      out.write("											<th>ဖော်ပြချက်</th>\r\n");
      out.write("											<th>logo</th>\r\n");
      out.write("											<th>ဓာတ်ပုံ</th>\r\n");
      out.write("											<th>Go to link</th>\r\n");
      out.write("											<th style=\"width: 40px\">Action</th>\r\n");
      out.write("										</tr>\r\n");
      out.write("									</thead>\r\n");
      out.write("									<tbody>\r\n");
      out.write("\r\n");
      out.write("										");

										int j = 0;

										for (pageUser user : userList) {
											String desc = user.getDesc();
										
      out.write("\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td>");
      out.print(user.getId());
      out.write("</td>\r\n");
      out.write("											<td>");
      out.print(user.getUniname());
      out.write("</td>\r\n");
      out.write("											<td>");
      out.print(user.getLocation());
      out.write("</td>\r\n");
      out.write("											<td>\r\n");
      out.write("												");
 if (desc != null && desc.length() > 50) { 
      out.write(' ');
      out.print( desc.substring(0, 20) );
      out.write("...\r\n");
      out.write("												");
 } else { 
      out.write(' ');
      out.print( desc );
      out.write(' ');
 } 
      out.write("\r\n");
      out.write("											</td>\r\n");
      out.write("											<td>");
      out.print(user.getLogo());
      out.write("</td>\r\n");
      out.write("											<td>");
      out.print(user.getImage());
      out.write("</td>\r\n");
      out.write("											<td><a href=\"../User/example.jsp?id=");
      out.print(user.getId());
      out.write("\">link</a>\r\n");
      out.write("											<td><a href=\"edit.jsp?id=");
      out.print(user.getId());
      out.write("\">Edit</a>\r\n");
      out.write("												<a\r\n");
      out.write("												onclick=\"alert('Are you sure you want to delete ?');\"\r\n");
      out.write("												href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pageDeleteUser?id=");
      out.print( user.getId() );
      out.write("\">Delete</a>\r\n");
      out.write("											</td>\r\n");
      out.write("										\r\n");
      out.write("											\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("										</tr>\r\n");
      out.write("										");

										j++;
										}
										
      out.write("\r\n");
      out.write("									</tbody>\r\n");
      out.write("								</table>\r\n");
      out.write("								<br>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				System.out.println("The list contains data.");
				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<aside class=\"control-sidebar control-sidebar-dark\">\r\n");
      out.write("			<!-- Control sidebar content goes here -->\r\n");
      out.write("			<div class=\"p-3\">\r\n");
      out.write("				<h5>Title</h5>\r\n");
      out.write("				<p>Sidebar content</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</aside>\r\n");
      out.write("		<!-- /.control-sidebar -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Main Footer -->\r\n");
      out.write("		<footer class=\"main-footer\">\r\n");
      out.write("			<!-- To the right -->\r\n");
      out.write("			<div class=\"float-right d-none d-sm-inline\">\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Default to the left -->\r\n");
      out.write("    <strong>Copyright &copy; 2023-2024 <a href=\"https://adminlte.io\">University Admissions Guide</a>.</strong> All rights reserved.\r\n");
      out.write("			</strong>\r\n");
      out.write("\r\n");
      out.write("		</footer>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"..//plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("	<!-- Bootstrap 4 -->\r\n");
      out.write("	<script src=\"../plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<!-- AdminLTE App -->\r\n");
      out.write("	<script src=\"../dist/js/adminlte.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
